id: tufm
module: tufm
label: 'Allows us to customize'
langcode: en
paths:
  - node/2
tips:
  introduction:
    id: introduction
    plugin: text
    label: 'Overview'
    body: '<p>This page shows all entries</p>'
    weight: 1